// Generated by CoffeeScript 1.6.3
var config, hapi, os, package_json;

package_json = require('./package');

hapi = require('hapi');

os = require('os');

config = {
  version: package_json.version,
  port: process.env.PORT || 8000,
  paths: {
    assets: "" + __dirname + "/assets"
  }
};

console.log('Server is running at http://' + os.hostname() + ":" + config.port);
