// Generated by CoffeeScript 1.6.3
var config, hapi, package_json, server, server_config;

package_json = require('./package');

hapi = require('hapi');

config = {
  version: package_json.version,
  port: Number(process.env.ENV_PORT) || 800,
  paths: {
    assets: "" + __dirname + "/assets"
  }
};

server_config = {
  views: {
    isCached: false,
    engines: {
      jade: 'jade'
    },
    path: "" + __dirname + "/"
  }
};

server = hapi.createServer('localhost', config.port, server_config);

module.exports = server;

server.route({
  path: '/assets/{path*}',
  method: 'get',
  handler: {
    directory: {
      listing: true,
      path: "" + __dirname + "/public/"
    }
  },
  config: {
    auth: false
  }
});

server.route({
  path: '/rest-api',
  method: 'get',
  handler: {
    view: './views/index'
  },
  config: {
    auth: false
  }
});

server.start();
