// Generated by CoffeeScript 1.6.3
var config, hapi, os, package_json, server, server_config;

package_json = require('./package');

hapi = require('hapi');

os = require('os');

config = {
  version: package_json.version,
  port: +process.env.PORT || 80,
  paths: {
    assets: "" + __dirname + "/assets"
  }
};

server_config = {
  views: {
    isCached: false,
    engines: {
      jade: 'jade'
    },
    path: "" + __dirname + "/"
  }
};

server = hapi.createServer(config.port, server_config);

server.route({
  path: '/assets/{path*}',
  method: 'get',
  handler: {
    directory: {
      listing: true,
      path: "" + __dirname + "/public/"
    }
  },
  config: {
    auth: false
  }
});

server.route({
  path: '/rest-api',
  method: 'get',
  handler: {
    view: './views/index'
  },
  config: {
    auth: false
  }
});

server.start(function() {
  return console.log('Server is running at http://' + os.hostname() + ":" + config.port);
});
